import React from "react";
import '@styles/global.css'
import Nav from "@components/Nav";
import Provider from "@components/Provider";
// import Provider from "@components/Provider";
export const metadata = {
    title: "PRMPTY",
    description: "Propmts for you",
};

const RootLayout = ({children}: { children: React.ReactNode }
    ) => {
        return (
            <html lang="en">
            <body>
            <Provider>
                <div className="main">
                    <div className="gradient"/>
                </div>
                <Nav/>
                <main className="app">{children}</main>
            </Provider>
            </body>
            </html>
        );
    }
;

export default RootLayout;

// import './globals.css'
// import { Inter } from 'next/font/google'
//
// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
//
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
